server: 
 port: 9002
spring:
   kafka:
     consumer:
        bootstrap-servers: localhost:9092
        group-id: group_id
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
     producer:
        bootstrap-servers: localhost:9092
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
   data:
     mongodb: 
       uri: mongodb+srv://{username}:{password}@cluster0.hyjjd.mongodb.net/order?retryWrites=true&w=majority
consumer:
   order:
    sequence: ordercapture,inventory,delivery,shipping,order
    reverse-sequence: default,reverse-inventory,order
   validation: 
    sequence: inventoryCheck,paymentCompletionCheck,addressValidCheck
validator:
   inventory-check: inventoryCheck
   payment-completion-check: paymentCompletionCheck
   address-valid-check: addressValidCheck
service:
   default-ms: default
   ordercapture-ms: ordercapture
   inventory-ms: inventory
   delivery-ms: delivery
   shipping-ms: shipping
   orderprocessor-ms: orderprocessor
   orderupdate-ms: order
   reverse-inventory-ms: reverse-inventory
raven:
   kafka:
     topic:
       orderupdate-ms-request: order
       inventory-ms-request: inventory
       delivery-ms-request: delivery
       shipping-ms-request: shipping
       orderprocessor-ms-response: processor 
       